part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Color tokens and theme extensions for the generated theme.
final FColors lightColors = FColors(
  brightness: .light,
  systemOverlayStyle: .dark,
  barrier: Color(0x33000000),
  background: Color(0xFFFFFFFF),
  foreground: Color(0xFF0C0A09),
  primary: Color(0xFF0069A8),
  primaryForeground: Color(0xFFF0F9FF),
  secondary: Color(0xFFF5F5F4),
  secondaryForeground: Color(0xFF1C1917),
  muted: Color(0xFFF5F5F4),
  mutedForeground: Color(0xFF79716B),
  destructive: Color(0xFFE7000B),
  destructiveForeground: Color(0xFFFAFAFA),
  error: Color(0xFFE7000B),
  errorForeground: Color(0xFFFAFAFA),
  card: Color(0xFFFFFFFF),
  border: Color(0xFFE7E5E4),
  extensions: const [AppColors()],
);

final FColors darkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: .light,
  barrier: Color(0x7A000000),
  // A slate blue-grey instead of near-black: background #1B2127, with the raised
  // surfaces (cards, secondary/muted fills) a step lighter in the same hue.
  background: Color(0xFF1B2127),
  foreground: Color(0xFFFAFAF9),
  primary: Color(0xFF00598A),
  primaryForeground: Color(0xFFF0F9FF),
  secondary: Color(0xFF283038),
  secondaryForeground: Color(0xFFFAFAF9),
  muted: Color(0xFF283038),
  mutedForeground: Color(0xFF9BA5B0),
  destructive: Color(0xFFFF6467),
  destructiveForeground: Color(0xFFFAFAFA),
  error: Color(0xFFFF6467),
  errorForeground: Color(0xFFFAFAFA),
  card: Color(0xFF222A31),
  border: Color(0x1AFFFFFF),
  extensions: const [AppColors()],
);

/// Provides convenient access to theme extensions on [FColors].
///
/// ```dart
/// final accent = context.theme.colors.app.accent; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final accent = context.theme.colors.accent; ✅
///
/// final accent = context.theme.colors.extension<AppColors>().accent; ❌
/// ```
extension FColorsExtensions on FColors {
  AppColors get app => extension<AppColors>();
}

/// Custom color tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
class AppColors extends ThemeExtension<AppColors> {
  // TODO: add your color fields here:
  // final Color accent;

  const AppColors();

  @override
  AppColors copyWith() => const AppColors();

  @override
  AppColors lerp(covariant AppColors? other, double t) {
    if (other == null) {
      return this;
    }
    return const AppColors();
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppColors && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}
